name: atics_group
channels:
  - defaults
dependencies:
  - pip=23.2.1
  - python=3.10.12
  - sentencepiece
  - pip:
      - faiss-cpu==1.7.4
      - torch==2.0.1
      - ir-measures==0.3.3
      - jupyter==1.0.0
      - pytest==7.4.0
      - tokenizers==0.21.1
      - transformers==4.51.3
      - datasets==3.6.0
      - numpy>=1.24.0 
      - accelerate
      - evaluate
      - scikit-learn
