#!/bin/bash
#SBATCH --job-name=finetuning_mt5
#SBATCH --output=logs/ft_mt5_smallbatch.out
#SBATCH --error=logs/ft_mt5_smallbatch.err
#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=06:00:00

module load 2023
module load Anaconda3/2023.07-2
conda activate atics_group

mkdir -p $HOME/BiasLLM/ft_mt5/results
mkdir -p $HOME/BiasLLM/ft_mt5/logs

#pip install --upgrade accelerate sentencepiece
#pip install --upgrade --force-reinstall --no-deps fsspec==2023.4.0 s3fs==2023.4.0


cd $HOME/BiasLLM/ft_mt5

python pretraining_mt5.py

