name: atics_p2
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.12
  - pip=23.2.1
  - pytorch=2.0.1
  - cudatoolkit=11.7
  - pip:
      - transformers==4.51.3
      - huggingface_hub>=0.16.4
      - safetensors
      - accelerate
      - peft
      - bitsandbytes>=0.39.0
      - faiss-cpu==1.7.4
      - ir-measures==0.3.3
      - jupyter==1.0.0
      - pytest==7.4.0
      - tokenizers==0.21.1
      - datasets==3.6.0
      - numpy>=1.24.0
      - sentencepiece
      - evaluate
      - scikit-learn==1.6.1
      - trl
      - wandb
      - flash-attn

