#!/bin/bash
#SBATCH --job-name=finetuning_mt5_oversample
#SBATCH --output=logs/finetuning_mt5_oversample_without.out
#SBATCH --error=logs/finetuning_mt5_oversample_without.err
#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=06:00:00

module load 2023
module load Anaconda3/2023.07-2
conda activate atics_p2
python pretraining_mt5_classification.py --sampling oversample --seed 45

