#!/bin/bash
#SBATCH --job-name=ft_mt5_undersample
#SBATCH --output=logs/ft_mt5_undersample_%A.out
#SBATCH --error=logs/ft_mt5_undersample_%A.err
#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=02:00:00

module purge
module load 2023
module load Anaconda3/2023.07-2

#  Proper shell initialization for Conda under Snellius
# eval "$(command conda 'shell.bash' 'hook' 2> /dev/null)"
source activate atics_p2

# echo "Installing correct transformers stack..."
pip install --upgrade --force-reinstall --no-cache-dir \
  numpy==1.26.4 \
  transformers==4.36.2 \
  tokenizers==0.15.2 \
  datasets==2.14.6 \
  accelerate==0.27.2 \
  huggingface-hub==0.22.2 \
  fsspec==2023.6.0
  
#  Confirm install worked
python -c "import transformers; print('Transformers is now available')"

cd $HOME/BiasLLM/mt5_classification

python pretraining_mt5_classification.py --sampling undersample --seed 50 --output_dir .runs/seed_50
#python pretraining_mt5_classification.py --sampling undersample --seed 51 --output_dir .runs/seed_51

echo "Done."