#!/bin/bash
#SBATCH --job-name=finetuning_mt5
#SBATCH --output=logs/ft_mt5.out
#SBATCH --error=logs/ft_mt5.err
#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=06:00:00

module load 2023
module load Anaconda3/2023.07-2
conda activate atics_group
pip install sentencepiece
pip install evaluate==0.4.1 datasets==2.18.0 huggingface_hub==0.20.3
pip install --upgrade accelerate
python pretraining_mt5.py

